sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
  - npm install codeclimate-test-reporter
script:
  - node_modules/.bin/ckeditor5-dev-tests-travis
after_success:
  - node_modules/.bin/codeclimate-test-reporter < .build/coverage/lcov.info
